=== Brotherta/wam-refont/pedalboard2/static/library_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "WAM Library Schema",
    "type": "object",
    "properties": {
        "name":{
            "description": "The name of the library",
            "type":"string"
        },
        "id":{
            "description": "The unique id of the library",
            "type":"string"
        },
        "version":{
            "description": "The version of the library",
            "type":"array", "items": [{"type":"number", "description": "Major"},{"type":"number", "description": "Minor"}]
        },
        "plugins":{
            "description": "A list of URLs to the index.js of the plugins in the library",
            "type":"array", "items": {"type":"string"}
        },
        "includes":{
            "description": "A list of library whose plugins are included in this library, with validation information",
            "type":"array",
            "items": {
                "type":"object",
                "properties": {
                    "url":{
                        "description": "The URL of the library json",
                        "type":"string"
                    },
                    "id":{
                        "description": "The expected unique id of the library",
                        "type":"string"
                    },
                    "version":{
                        "description": "The expected version of the library",
                        "type":"array", "items": [{"type":"number", "description": "Major"},{"type":"number", "description": "Minor"}]
                    }
                }
            }
        }
    }
}

=== Brotherta/wam-refont/bank/pedalboard2/static/local_library.t.json
{
    "$schema": "../../pedalboard2/static/library_schema.json",
    "name": "Legacy Pedalboard Library",
    "id": "wamstudio.pedalboard2.legacy",
    "version": [0,0],
    "plugins": [
        "{{HOSTNAME}}/plugins/BigMuff/index.js",
        "{{HOSTNAME}}/plugins/blipper/index.js",
        "{{HOSTNAME}}/plugins/CompressorGuitarix/index.js",
        "{{HOSTNAME}}/plugins/deathgate/index.js",
        "{{HOSTNAME}}/plugins/disto_machine/src/index.js",
        "{{HOSTNAME}}/plugins/DualPitchShifter/index.js",
        "{{HOSTNAME}}/plugins/graphicEqualizer/index.js",
        "{{HOSTNAME}}/plugins/greyhole/index.js",
        "{{HOSTNAME}}/plugins/GuitarAmpSim60s/index.js",
        "{{HOSTNAME}}/plugins/BigMuff/index.js",
        "{{HOSTNAME}}/plugins/kbverb/index.js",
        "{{HOSTNAME}}/plugins/Kpp_fuzz/index.js",
        "{{HOSTNAME}}/plugins/kppdistorder/index.js",
        "{{HOSTNAME}}/plugins/BigMuff/index.js",
        "{{HOSTNAME}}/plugins/Octaver/index.js",
        "{{HOSTNAME}}/plugins/OscTube/index.js",
        "{{HOSTNAME}}/plugins/OverdriveRix/index.js",
        "{{HOSTNAME}}/plugins/OwlDirty/index.js",
        "{{HOSTNAME}}/plugins/OwlShimmer/index.js",
        "{{HOSTNAME}}/plugins/SmoothDelay/index.js",
        "{{HOSTNAME}}/plugins/StereoFreqShifter/index.js",
        "{{HOSTNAME}}/plugins/stonephaser/index.js",
        "{{HOSTNAME}}/plugins/StonePhaserStereo/index.js",
        "{{HOSTNAME}}/plugins/sweetWah/index.js",
        "{{HOSTNAME}}/plugins/temper/index.js",
        "{{HOSTNAME}}/plugins/ThruZeroFlanger/index.js",
        "{{HOSTNAME}}/plugins/TS9_OverdriveFaustGenerated/index.js",
        "{{HOSTNAME}}/plugins/WeirdPhaser/index.js"
    ],
    "includes": []
}

=== Brotherta/wam-refont/bank/plugins/library.json
{
    "$schema": "../../pedalboard2/static/library_schema.json",
    "name": "Legacy Pedalboard Library",
    "id": "wamstudio.pedalboard2.legacy",
    "version": [0,0],
    "plugins": [
        "/plugins/BigMuff/index.js",
        "/plugins/blipper/index.js",
        "/plugins/CompressorGuitarix/index.js",
        "/plugins/deathgate/index.js",
        "/plugins/disto_machine/src/index.js",
        "/plugins/DualPitchShifter/index.js",
        "/plugins/graphicEqualizer/index.js",
        "/plugins/greyhole/index.js",
        "/plugins/GuitarAmpSim60s/index.js",
        "/plugins/BigMuff/index.js",
        "/plugins/kbverb/index.js",
        "/plugins/Kpp_fuzz/index.js",
        "/plugins/kppdistorder/index.js",
        "/plugins/BigMuff/index.js",
        "/plugins/Octaver/index.js",
        "/plugins/OscTube/index.js",
        "/plugins/OverdriveRix/index.js",
        "/plugins/OwlDirty/index.js",
        "/plugins/OwlShimmer/index.js",
        "/plugins/SmoothDelay/index.js",
        "/plugins/StereoFreqShifter/index.js",
        "/plugins/stonephaser/index.js",
        "/plugins/StonePhaserStereo/index.js",
        "/plugins/sweetWah/index.js",
        "/plugins/temper/index.js",
        "/plugins/ThruZeroFlanger/index.js",
        "/plugins/TS9_OverdriveFaustGenerated/index.js",
        "/plugins/WeirdPhaser/index.js"
    ],
    "includes": []
}
